import './ui/global.css';

import { inter } from './ui/font';
import Providers from './providers';
import ThemeSwitcher from './ui/dashboard/header/ThemeSwitcher';

export const metadata = {
  title: 'VGR',
  description: 'Generated by Next.js 14',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{ colorScheme: 'light' }}>
      <body
        className={`${inter.className} max-w-custom-vw scroll-pt-top relative  m-0 min-h-full`}
      >
        <Providers>
          <div className="relative min-h-screen">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
